### PR TITLE
Feature/call graph generation

### PR DESCRIPTION
**Pull request by almacken**

### CODE REVIEW

**Comment by almacken** [comment]
I'm currently trying to fix the errors in this version and improve code quality.
I'll add another comment when this branch is ready to merge.

**Comment by almacken** [comment]
I'm currently trying to fix the errors in this version and improve code quality.
I'll add another comment when this branch is ready to merge.

**Comment by almacken** [comment]
Many of the bugs I'm fixing are caused by usage of Elastic4s' ElasticClient class, which does not appear to actually exist in the copy of the library I have on my machine.
I'm currently replacing usages of it with HttpClient, and updating some code to support differences in return types.

**Comment by almacken** [comment]
The Travis CI build doesn't seem able to resolve references to either ElasticClient or HttpClient.
Does anyone know what the issue here is?

**Comment by bhermann** [comment]
Please try again in your environment with activated auto-import (see email).

**Comment by almacken** [comment]
Alright, I think that's all the changes I'm going to make.
This branch is ready to be merged.

**Comment by bhermann** [comment]
Thanks Alex! I'll have look tomorrow. Just made it home after some travel chaos.

**Pull request merged**
